-- WP-BE-01.1 baseline schema (design document §27.4).
--
-- Deliberately the THIN first slice: credentials, OIDC clients, sessions,
-- refresh-token families and the security epoch. Passkeys, TOTP, recovery
-- codes, devices and email verification arrive in WP-BE-01.2.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(320) NOT NULL UNIQUE,
    display_name  VARCHAR(120) NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL
);

-- Credentials are separate from users so multiple credential types and a
-- rotation history are possible (design document §27.5).
CREATE TABLE credentials (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    credential_type    VARCHAR(32) NOT NULL,          -- PASSWORD | ...
    secret_hash        VARCHAR(255) NOT NULL,         -- Argon2id
    credential_version BIGINT      NOT NULL DEFAULT 1,
    created_at         TIMESTAMP   NOT NULL
);
CREATE INDEX idx_credentials_user ON credentials (user_id);

-- Reuse prevention (design document §27.5).
CREATE TABLE password_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    secret_hash VARCHAR(255) NOT NULL,
    retired_at  TIMESTAMP    NOT NULL
);
CREATE INDEX idx_password_history_user ON password_history (user_id);

-- ADR-SEC-009: the continuous-verification watermark.
CREATE TABLE user_security_state (
    user_id            BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    token_valid_after  TIMESTAMP,
    credential_version BIGINT      NOT NULL DEFAULT 1,
    account_status     VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    risk_level         VARCHAR(32),
    updated_at         TIMESTAMP   NOT NULL
);

-- ADR-SEC-011: server-side sessions; the BFF anchors its cookie here.
CREATE TABLE security_sessions (
    id                   VARCHAR(64) PRIMARY KEY,
    user_id              BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    device_id            VARCHAR(64),
    refresh_family_id    VARCHAR(36),
    auth_time            TIMESTAMP   NOT NULL,
    last_seen_at         TIMESTAMP   NOT NULL,
    authentication_level VARCHAR(32) NOT NULL,
    risk_score           INT,
    status               VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    expires_at           TIMESTAMP   NOT NULL,
    created_ip_hash      VARCHAR(64),
    last_ip_hash         VARCHAR(64),
    user_agent_hash      VARCHAR(64)
);
CREATE INDEX idx_sessions_user ON security_sessions (user_id);

-- ADR-SEC-010: family is its own entity so a reuse incident can record the
-- reason, actor and time - forensic detail a column cannot hold.
CREATE TABLE refresh_token_families (
    id                VARCHAR(36) PRIMARY KEY,
    user_id           BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at        TIMESTAMP   NOT NULL,
    revoked_at        TIMESTAMP,
    revocation_reason VARCHAR(64)
);
CREATE INDEX idx_families_user ON refresh_token_families (user_id);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,   -- SHA-256; raw value never stored
    family_id  VARCHAR(36) NOT NULL REFERENCES refresh_token_families (id) ON DELETE CASCADE,
    expires_at TIMESTAMP   NOT NULL,
    revoked    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP   NOT NULL
);
CREATE INDEX idx_refresh_family ON refresh_tokens (family_id);

-- ADR-SEC-015: tenancy. Resource tenancy is derived from the stored record and
-- checked against explicit membership; a tenant id in a request is never proof.
CREATE TABLE tenants (
    id         VARCHAR(36) PRIMARY KEY,
    name       VARCHAR(160) NOT NULL,
    status     VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP    NOT NULL
);

CREATE TABLE subject_tenant_membership (
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    tenant_id  VARCHAR(36) NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    role       VARCHAR(64) NOT NULL,
    granted_at TIMESTAMP   NOT NULL,
    PRIMARY KEY (user_id, tenant_id)
);

CREATE TABLE oauth_clients (
    id                     VARCHAR(36)  PRIMARY KEY,
    client_id              VARCHAR(160) NOT NULL UNIQUE,
    client_secret_hash     VARCHAR(255),
    client_name            VARCHAR(160) NOT NULL,
    authentication_methods VARCHAR(512) NOT NULL,
    grant_types            VARCHAR(512) NOT NULL,
    redirect_uris          VARCHAR(2000),
    scopes                 VARCHAR(1000),
    require_pkce           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at             TIMESTAMP    NOT NULL
);

-- ADR-SEC-023: security telemetry. Token values are never written here.
CREATE TABLE security_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type   VARCHAR(64)  NOT NULL,
    subject      VARCHAR(320),
    session_id   VARCHAR(64),
    tenant_id    VARCHAR(36),
    decision     VARCHAR(16),
    policy_id    VARCHAR(64),
    policy_ver   VARCHAR(32),
    reason_code  VARCHAR(64),
    trace_id     VARCHAR(64),
    ip_hash      VARCHAR(64),
    occurred_at  TIMESTAMP    NOT NULL
);
CREATE INDEX idx_events_subject ON security_events (subject, occurred_at);
CREATE INDEX idx_events_type ON security_events (event_type, occurred_at);
