-- ADR-SEC-015 / design document §24.3, §27.5.
--
-- Tenant isolation is server-enforced: a tenant identifier arriving in a
-- request is context, never proof. Resource tenancy is derived from the stored
-- record and checked against explicit membership, so these tables must exist
-- before WP-BE-02 can enforce anything. The v1.5 review found them missing from
-- the proposed model entirely - a work package cannot implement what an earlier
-- one never created.

CREATE TABLE tenants (
    id         VARCHAR(36)  PRIMARY KEY,
    name       VARCHAR(160) NOT NULL,
    status     VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP    NOT NULL
);

-- Membership is explicit and relational. Absence of a row is denial; there is
-- no implicit or inherited membership, and no "admin sees everything" path.
CREATE TABLE subject_tenant_membership (
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    tenant_id  VARCHAR(36) NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    role       VARCHAR(64) NOT NULL,
    granted_at TIMESTAMP   NOT NULL,
    PRIMARY KEY (user_id, tenant_id)
);

CREATE INDEX idx_membership_tenant ON subject_tenant_membership (tenant_id);

-- Credential reuse prevention (§27.5). The credentials table itself - splitting
-- the password hash out of users to support multiple credential types - is
-- WP-BE-01.2 work; this is the part the current model can carry today.
CREATE TABLE password_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    secret_hash VARCHAR(255) NOT NULL,
    retired_at  TIMESTAMP    NOT NULL
);

CREATE INDEX idx_password_history_user ON password_history (user_id);
